compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  midnight-ntwrk:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://npm.pkg.github.com/"
    npmRegistryServer: "https://npm.pkg.github.com/"

yarnPath: .yarn/releases/yarn-4.10.3.cjs

changesetBaseRefs: [
  "origin/main"
]
