/*
 * This file is part of midnight-js.
 * Copyright (C) Midnight Foundation
 * SPDX-License-Identifier: Apache-2.0
 * Licensed under the Apache License, Version 2.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Regenerates every derived/minted OQ9 fixture from the two committed
// goldens (state-v8-v6-envelope.hex, state-migrated-v9.hex) and the compiled
// twin-contract/. Run with: `node generate-all.mjs` from this directory, or
// `node testkit-js/testkit-js/src/fixtures/hf/generators/generate-all.mjs`
// from the repo root. See ../README.md for what each fixture is and why.
//
// NOT regenerated by this script (see ../README.md for provenance):
//   - state-v8-v6-envelope.hex and state-migrated-v9.hex are golden copies
//     ported from spike-dapp-hf/island-3; there is no generator for them here.
//   - twin-contract/compiled/** is compiled by running compactc directly
//     (see ../README.md "twin-contract"), not by a mint script.

import { run as mintStateV8 } from './mint-state-v8.mjs';
import { run as mintMigratedV9Merkle } from './mint-migrated-v9-merkle.mjs';
import { run as mintTamperedAndDerived } from './mint-tampered-and-derived.mjs';
import { run as mintCoV2Foreign } from './mint-co-v2-foreign.mjs';

mintStateV8();
mintMigratedV9Merkle();
mintTamperedAndDerived();
mintCoV2Foreign();
