#!/usr/bin/env bash

# This file is part of midnight-js.
# Copyright (C) 2025-2026 Midnight Foundation
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Build compactc from the `compact/` git submodule via nix and write a
# COMPACT_HOME wrapper that packages/compact `run-compactc` uses (skipping the
# prebuilt-binary download). Use this for feature-branch development against
# unreleased compactc changes.
#
# The wrapper bakes the version-locked zkir/zkir-v3 onto PATH so an unrelated
# zkir elsewhere on PATH cannot be picked up (which would silently emit
# incompatible proving keys).
#
# The build is kept alive by a gcroot symlink (.compact-home/result), so the
# wrapper keeps working after `nix-collect-garbage`. First build can be slow:
# without nix `trusted-users` access to the IOG cache (cache.iog.io), zkir is
# compiled from source. It is cached afterwards.

set -euo pipefail

# shellcheck source=./lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
cd "$REPO_ROOT"

assert_submodule_initialized
assert_command nix "building compactc from the submodule"

# Output directory for the wrapper + nix gcroot. Defaults to `.compact-home`
# at the repo root; `scripts/build-compactc-docker.sh` overrides it via
# COMPACT_BUILD_OUT to install the bundle outside its runtime bind-mount target.
home="${COMPACT_BUILD_OUT:-${REPO_ROOT}/.compact-home}"
mkdir -p "$home"

# Default flake reference: `path:` works with paths containing spaces and
# without a `.git` (unlike `git+file://`). Overridable via COMPACTC_FLAKE_REF.
flake_ref="${COMPACTC_FLAKE_REF:-$(default_compact_flake_ref)}"

# --out-link registers an indirect gcroot, so the built compiler survives
# `nix-collect-garbage` and the wrapper keeps pointing at a live store path.
echo "Building compactc from ${flake_ref} (first build can be slow)..."
nix build --out-link "$home/result" "${flake_ref}#compactc-binary"

cat > "$home/compactc" <<EOF
#!/usr/bin/env bash
# Generated by scripts/build-compactc.sh — do not edit.
export PATH="${home}/result/lib:\$PATH"
exec "${home}/result/bin/compactc.bin" "\$@"
EOF
chmod +x "$home/compactc"

echo "compactc $("$home/compactc" --version) ready"
echo "COMPACT_HOME=${home} (exported automatically in the dev shell / direnv)"
