#!/usr/bin/env bash

# This file is part of midnight-js.
# Copyright (C) 2025-2026 Midnight Foundation
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Build compactc from the `compact/` submodule inside a Docker container, so
# developers without nix on the host can still test against an unreleased
# compactc feature branch. The result is a host wrapper at
# `.compact-home/compactc` that proxies each invocation into a built image.
#
# Requires only Docker on the host (no nix). Trade-off: each `compactc`
# invocation pays Docker startup overhead (~1-2s on macOS). For nix-native
# host builds (faster, no per-invocation overhead) use `./scripts/build-compactc.sh`.

set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$repo_root"

if [ ! -f compact/flake.nix ]; then
  echo "error: compact submodule not initialized. Run: git submodule update --init compact" >&2
  exit 1
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "error: docker is required to build compactc without host nix." >&2
  exit 1
fi

home="${repo_root}/.compact-home"
mkdir -p "$home"

image_tag="midnight-js-compactc-local:latest"
echo "Building compactc Docker image '$image_tag' (first build can be slow)..."

# Use a heredoc Dockerfile; build context is the compact/ submodule.
# Append (don't clobber) so the base image's defaults survive. `extra-` merges
# onto defaults. sandbox=false because container runtimes usually lack the
# user namespaces nix's sandbox needs. IOG cache provides zkir prebuilt.
docker build --tag "$image_tag" --file - "$repo_root/compact" <<'DOCKERFILE'
FROM nixos/nix:latest
RUN mkdir -p /etc/nix && { \
    echo "extra-experimental-features = nix-command flakes"; \
    echo "sandbox = false"; \
    echo "extra-substituters = https://cache.iog.io"; \
    echo "extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ="; \
  } >> /etc/nix/nix.conf
COPY . /work/compact
WORKDIR /work
RUN nix build "path:/work/compact#compactc-binary" --out-link /tmp/result
RUN store="$(readlink -f /tmp/result)" && \
    mkdir -p /compact-home/bin /compact-home/lib && \
    cp -L "$store"/bin/* /compact-home/bin/ && \
    cp -L "$store"/lib/* /compact-home/lib/ && \
    printf '#!/usr/bin/env bash\nexport PATH=/compact-home/lib:$PATH\nexec /compact-home/bin/compactc.bin "$@"\n' > /compact-home/compactc && \
    chmod +x /compact-home/compactc
ENTRYPOINT ["/compact-home/compactc"]
DOCKERFILE

# Host wrapper. run-compactc invokes `$COMPACT_HOME/compactc <args>` where args
# are file paths relative to the package's CWD. We mount that CWD into /work
# and run the container with the same workdir so relative paths resolve.
# --user keeps generated files owned by the host user (not root).
cat > "$home/compactc" <<EOF
#!/usr/bin/env bash
# Generated by scripts/build-compactc-docker.sh — do not edit.
exec docker run --rm \\
  --user "\$(id -u):\$(id -g)" \\
  --volume "\$PWD:/work" \\
  --workdir /work \\
  "$image_tag" "\$@"
EOF
chmod +x "$home/compactc"

echo "compactc Docker wrapper ready at $home/compactc"
echo "COMPACT_HOME=$home (.envrc auto-exports it after direnv reload)"
