#!/usr/bin/env bash

# This file is part of midnight-js.
# Copyright (C) 2025-2026 Midnight Foundation
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Build compactc from the `compact/` submodule inside a Docker container, so
# developers without nix on the host can still test against an unreleased
# compactc feature branch. The result is a host wrapper at
# `.compact-home/compactc` that proxies each invocation into the built image.
#
# The image's actual build step delegates to `scripts/build-compactc.sh` so the
# nix-build + bundle-extraction logic lives in one place (this script only
# handles the docker plumbing).
#
# Requires only Docker on the host (no nix). Trade-off: each `compactc`
# invocation pays Docker startup overhead (~1-2s on macOS). For nix-native
# host builds (faster, no per-invocation overhead) use `./scripts/build-compactc.sh`.

set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$repo_root"

if [ ! -f compact/flake.nix ]; then
  echo "error: compact submodule not initialized. Run: git submodule update --init compact" >&2
  exit 1
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "error: docker is required to build compactc without host nix." >&2
  exit 1
fi

home="${repo_root}/.compact-home"
mkdir -p "$home"

image_tag="midnight-js-compactc-local:latest"
echo "Building compactc Docker image '$image_tag' (first build can be slow)..."

# Build context = repo root, narrowed by the repo-root `.dockerignore` to
# `scripts/` and `compact/` (minus compact/.git). The Dockerfile invokes the
# same scripts/build-compactc.sh we use for native nix builds, so the
# extraction logic and wrapper layout live in one place.
#
# The compactc bundle is installed at /compactc-home (NOT /work/.compact-home)
# so the runtime bind-mount of the caller's CWD to /host-cwd cannot shadow it.
docker build --tag "$image_tag" --file - "$repo_root" <<'DOCKERFILE'
FROM nixos/nix:latest
# Append (don't clobber) so the base image's defaults survive. `extra-` merges
# onto those defaults. sandbox=false because container runtimes usually lack
# the user namespaces nix's sandbox needs. IOG cache provides zkir prebuilt.
RUN mkdir -p /etc/nix && { \
    echo "extra-experimental-features = nix-command flakes"; \
    echo "sandbox = false"; \
    echo "extra-substituters = https://cache.iog.io"; \
    echo "extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ="; \
  } >> /etc/nix/nix.conf
COPY scripts/build-compactc.sh /opt/build-compactc/scripts/build-compactc.sh
COPY compact /opt/build-compactc/compact
WORKDIR /opt/build-compactc
# `git+file://` flake ref needs a `.git` (excluded by .dockerignore), so use
# the path-flake override `scripts/build-compactc.sh` already supports.
ENV COMPACTC_FLAKE_REF=path:/opt/build-compactc/compact
# Direct the script to lay the bundle outside the host bind-mount target.
ENV COMPACT_BUILD_OUT=/compactc-home
RUN /opt/build-compactc/scripts/build-compactc.sh
ENTRYPOINT ["/compactc-home/compactc"]
DOCKERFILE

# Host wrapper. run-compactc invokes `$COMPACT_HOME/compactc <args>` where
# args are paths relative to the package's CWD. Mount that CWD at /host-cwd
# and run the container with --workdir /host-cwd so relative paths resolve.
# --user keeps generated files owned by the host user (not root).
cat > "$home/compactc" <<EOF
#!/usr/bin/env bash
# Generated by scripts/build-compactc-docker.sh — do not edit.
exec docker run --rm \\
  --user "\$(id -u):\$(id -g)" \\
  --volume "\$PWD:/host-cwd" \\
  --workdir /host-cwd \\
  "$image_tag" "\$@"
EOF
chmod +x "$home/compactc"

echo "compactc Docker wrapper ready at $home/compactc"
echo "COMPACT_HOME=$home (.envrc auto-exports it after direnv reload)"
