name: CI
env:
  MIDNIGHTCI_PACKAGES_WRITE: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      build_mn_js: ${{ steps.build-targets.outputs.build_mn_js }}
      build_c_js: ${{ steps.build-targets.outputs.build_c_js }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # ratchet:actions/setup-node@v4
        with:
          always-auth: true
          registry-url: https://npm.pkg.github.com/
          scope: '@midnight-ntwrk'
          node-version-file: '.nvmrc'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}

      - name: Determine Build Targets
        id: build-targets
        run: |
          build_mn_js=$(yarn workspaces list --since --json | jq -s '([.[] | select(.location != ".") | .location | split("/")[0]] | unique) | index("packages") != null')
          build_c_js=$(yarn workspaces list --since --json | jq -s '([.[] | select(.location != ".") | .location | split("/")[0]] | unique) | index("compact-js") != null')
          
          echo "build_mn_js=${build_mn_js}" >> "$GITHUB_OUTPUT"
          echo "build_c_js=${build_c_js}" >> "$GITHUB_OUTPUT"

          echo "### Build Target Summary" >> $GITHUB_STEP_SUMMARY
          echo "The following table summarizes which targets have changes detected in them and that will be included in the build." >> $GITHUB_STEP_SUMMARY
          echo "| Target      | Changed        |" >> $GITHUB_STEP_SUMMARY
          echo "| ----------- | -------------- |" >> $GITHUB_STEP_SUMMARY
          echo "| Midnight.js | ${build_mn_js} |" >> $GITHUB_STEP_SUMMARY
          echo "| Compact.js  | ${build_c_js}  |" >> $GITHUB_STEP_SUMMARY

  ci-mnjs:
    needs: ci
    name: Build Midnight.js
    uses: ./.github/workflows/ci_mn_js.yml
    with:
      should_run: 'false'
      # should_run: ${{ needs.ci.outputs.build_mn_js }}
      should_prerelease: 'false'
    secrets: inherit

  ci-cjs:
    needs: ci
    name: Build Compact.js
    with:
      should_run: ${{ needs.ci.outputs.build_c_js }}
      should_prerelease: ${{ 
          (github.event_name != 'schedule' &&
          (github.ref_name == 'main' || contains(github.event.head_commit.message, '[do_publish]') || github.event_name == 'workflow_dispatch'))
            && 'true' || 'false'
        }}
    uses: ./.github/workflows/ci_c_js.yml
    secrets: inherit
