name: CI - Compact.js
env:
  MIDNIGHTCI_PACKAGES_WRITE: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      should_run:
        required: true
        type: string

concurrency:
  group: C-JS-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    if: inputs.should_run == 'true'
    uses: ./.github/workflows/ci_base.yml
    with:
      yarn_filter: --filter="./compact-js/*"
      yarn_lint_paths: ./compact-js
      network: undeployed
      allure_upload: true
      allure_project_id: midnight-js-main
    secrets: inherit
