name: License Header Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  license-header:
    name: Check License Headers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  #v5.0.0

      - name: Check License Headers
        uses: apache/skywalking-eyes/header@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  license-header-fix:
    name: Fix License Headers (Create PR)
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  #v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fix License Headers
        uses: apache/skywalking-eyes/header@main
        with:
          mode: fix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "fix: add missing license headers"
          title: "Fix missing license headers"
          body: |
            This PR automatically fixes missing license headers in the codebase.

            Generated by license-headers workflow.
          branch: fix/license-headers
          delete-branch: true
